# Generated by Django 4.2.11 on 2024-06-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classdatamodel',
            fields=[
                ('Class_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ClassDataModel',
            },
        ),
        migrations.CreateModel(
            name='Schooldatamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('passkey', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('category', models.CharField(choices=[('A++', 'A++'), ('A+', 'A+'), ('A', 'A')], max_length=3)),
            ],
            options={
                'verbose_name': 'SchoolDataModel',
                'verbose_name_plural': 'SchoolDataModel',
                'db_table': 'SchoolDataModel',
            },
        ),
        migrations.CreateModel(
            name='Subjectdatamodel',
            fields=[
                ('Subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'SubjectDataModel',
                'verbose_name_plural': 'SubjectDataModel',
                'db_table': 'SubjectDataModel',
                'ordering': ['Subject_ID'],
                'unique_together': {('name', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Studentdatamodel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('passportphoto', models.ImageField(upload_to='UserUploadedFiles/')),
                ('adharphoto', models.ImageField(null=True, upload_to='UserUploadedFiles/')),
                ('fathername', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('parentmobile', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('id_valid_till', models.DateField(null=True)),
                ('registered_student', models.BooleanField(default=False)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageSchool.classdatamodel')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageSchool.schooldatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='Staffdatamodel',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=100)),
                ('steert', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hire_date', models.DateField()),
                ('id_valid_till', models.DateField(null=True)),
                ('registered_staff', models.BooleanField(default=False)),
                ('subject_to_tought', models.ManyToManyField(blank=True, to='ManageSchool.subjectdatamodel')),
            ],
        ),
        migrations.AddField(
            model_name='classdatamodel',
            name='subjects_assigned',
            field=models.ManyToManyField(to='ManageSchool.subjectdatamodel'),
        ),
    ]
