# Generated by Django 5.0.6 on 2024-08-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageSchool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdatamodel',
            name='steert',
        ),
        migrations.AddField(
            model_name='staffdatamodel',
            name='adharphoto',
            field=models.ImageField(null=True, upload_to='UserUploadedFiles/'),
        ),
        migrations.AddField(
            model_name='staffdatamodel',
            name='passportphoto',
            field=models.ImageField(null=True, upload_to='UserUploadedFiles/'),
        ),
        migrations.AddField(
            model_name='staffdatamodel',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='staffdatamodel',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffdatamodel',
            name='qualification_certificate',
            field=models.ImageField(null=True, upload_to='UserUploadedFiles/'),
        ),
        migrations.AlterModelTable(
            name='staffdatamodel',
            table='StaffDataModel',
        ),
    ]
