# Generated by Django 4.2.11 on 2024-03-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageSchool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdatamodel',
            name='Student_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
