# Generated by Django 5.0.6 on 2024-08-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageSchool', '0004_alter_staffdatamodel_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldatamodel',
            name='About',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='schooldatamodel',
            name='Tagline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooldatamodel',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
