# Generated by Django 5.1.2 on 2025-02-04 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_principal'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_principal', to='staffs.staff'),
        ),
    ]
