# Generated by Django 5.1.2 on 2025-02-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
