# Generated by Django 5.1.2 on 2025-02-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adharcard',
            field=models.FileField(blank=True, null=True, upload_to='documents/adharcard/'),
        ),
        migrations.AddField(
            model_name='student',
            name='passportphoto',
            field=models.ImageField(blank=True, null=True, upload_to='documents/passportphoto/'),
        ),
        migrations.AddField(
            model_name='student',
            name='tc',
            field=models.FileField(blank=True, null=True, upload_to='documents/tc/'),
        ),
    ]
