# Generated by Django 5.1.2 on 2025-02-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_adharcard_student_passportphoto_student_tc'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('adharcard', models.FileField(blank=True, null=True, upload_to='registration_documents/adharcard/')),
                ('tc', models.FileField(blank=True, null=True, upload_to='registration_documents/tc/')),
                ('passportphoto', models.ImageField(blank=True, null=True, upload_to='registration_documents/passportphoto/')),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Student Registration',
                'verbose_name_plural': 'Student Registrations',
                'db_table': 'student_registrations',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
