# Generated by Django 5.1.2 on 2025-02-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_principal'),
        ('students', '0003_studentregistration_alter_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
